import { useEffect } from "react";
import Head from "next/head";
import {
  useDyteClient,
  useDyteMeeting,
  DyteProvider,
} from "@dytesdk/react-web-core";
import { DyteMeeting, DyteAudioVisualizer } from "@dytesdk/react-ui-kit";

import styles from "../styles/Home.module.css";

function MyMeeting() {
  const { meeting } = useDyteMeeting();

  return (
    <DyteMeeting
      mode="fill"
      meeting={meeting}
      style={{ height: "100vh", width: "100vw" }}
      showSetupScreen={true}
    />
  );
}

function Home({ roomName, authToken }) {
  const [meeting, initMeeting] = useDyteClient();

  useEffect(() => {
    initMeeting({
      roomName,
      authToken,
      defaults: {
        audio: true,
        video: true,
      },
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Dyte Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DyteProvider value={meeting}>
        <MyMeeting />
      </DyteProvider>
    </div>
  );
}

Home.getInitialProps = async function getInitialProps(ctx) {
  const { roomName, authToken } = ctx.query;

  return { roomName, authToken };
};

export default Home;
